version: '2.0'

services:
    prometheus:
        container_name: prometheus
        image: prom/prometheus:latest
        volumes:
            - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        ports:
            - 9090:9090
        network_mode: host

    grafana:
        container_name: grafana
        image: grafana/grafana:latest
        volumes:
            - /var/lib/grafana:/var/lib/grafana
        ports:
            - 3000:3000
        network_mode: host

    gcu-exporter:
        container_name: gcu-exporter
        image: artifact.enflame.cn/enflame_docker_images/enflame/gcu-exporter:latest
        privileged: true
        volumes:
            - /usr/lib/libefml.so:/usr/lib/libefml.so
            - /usr/local/efsmi:/usr/local/efsmi
        ports:
            - 9400:9400
        network_mode: host
